general.import = ["theme.toml", "globals.toml"]

[window]
opacity = 1.0

[terminal]
shell = "/bin/bash"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#normal = { family = "creep", style = "Regular" }
#normal = { family = "cozette", style = "Regular" }
#bold = { family = "cozette", style = "Regular" }
#size = 12.0
size = 11.0
