#!/bin/sh

# Mod1+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Mod1 Return spawn alacritty

# File manager
riverctl map normal Mod1 E spawn "thunar"

# Launcher
riverctl map normal Mod1 D spawn "fuzzel"

# Focus mode
riverctl map normal Mod4 F spawn "swww kill && riverctl background-color 0x0f302a"

# Normal mode
riverctl map normal Mod4 N spawn "swww-daemon && swww restore"

# Mod1+Q to close the focused view
riverctl map normal Mod1+Shift Q close

# Mod1+Shift+E to exit river
riverctl map normal Mod1+Shift M exit

# Mod1+J and Mod1+K to focus the next/previous view in the layout stack
riverctl map normal Mod1 J focus-view next
riverctl map normal Mod1 K focus-view previous

# Mod1+Shift+J and Mod1+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Mod1+Shift J swap next
riverctl map normal Mod1+Shift K swap previous

# Mod1+Period and Mod1+Comma to focus the next/previous output
riverctl map normal Mod1 Period focus-output next
riverctl map normal Mod1 Comma focus-output previous

# Mod1+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Mod1+Shift Period send-to-output next
riverctl map normal Mod1+Shift Comma send-to-output previous

# Mod1+Return to bump the focused view to the top of the layout stack
riverctl map normal Mod1+Shift Return zoom

# Mod1+H and Mod1+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Mod1 H send-layout-cmd wideriver "--ratio -0.05"
riverctl map normal Mod1 L send-layout-cmd wideriver "--ratio +0.05"

# Mod1+Shift+H and Mod1+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Mod1+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Mod1+Shift L send-layout-cmd rivertile "main-count -1"

# Mod1+Alt+{H,J,K,L} to move views
# riverctl map normal Mod1+Alt H move left 100
# riverctl map normal Mod1+Alt J move down 100
# riverctl map normal Mod1+Alt K move up 100
# riverctl map normal Mod1+Alt L move right 100

# Mod1+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Mod1+Alt+Control H snap left
# riverctl map normal Mod1+Alt+Control J snap down
# riverctl map normal Mod1+Alt+Control K snap up
# riverctl map normal Mod1+Alt+Control L snap right

# Mod1+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal Mod1+Alt+Shift H resize horizontal -100
# riverctl map normal Mod1+Alt+Shift J resize vertical 100
# riverctl map normal Mod1+Alt+Shift K resize vertical -100
# riverctl map normal Mod1+Alt+Shift L resize horizontal 100

# Mod1 + Left Mouse Button to move views
riverctl map-pointer normal Mod1 BTN_LEFT move-view

# Mod1 + Right Mouse Button to resize views
riverctl map-pointer normal Mod1 BTN_RIGHT resize-view

# Mod1 + Middle Mouse Button to toggle float
riverctl map-pointer normal Mod1 BTN_MIDDLE toggle-float

for i in $(seq 1 6)
do
    tags=$((1 << ($i - 1)))

    # Mod1+[1-9] to focus tag [0-8]
    riverctl map normal Mod1 $i set-focused-tags $tags

    # Mod1+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Mod1+Shift $i set-view-tags $tags

    # Mod1+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Mod1+Control $i toggle-focused-tags $tags

    # Mod1+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Mod1+Shift+Control $i toggle-view-tags $tags
done

riverctl map normal Mod1+Shift Z spawn "riverctl send-to-output -current-tags DP-2"
riverctl map normal Mod1+Shift X spawn "riverctl send-to-output -current-tags HDMI-A-1"

riverctl map normal Mod1 1 spawn "riverctl focus-output DP-2; riverctl set-focused-tags $((1 << (1 - 1)))"
# riverctl map normal Mod1+Shift 1 spawn "riverctl focus-output DP-2; riverctl set-view-tags $((1 << (1 - 1)))"
riverctl map normal Mod1 2 spawn "riverctl focus-output DP-2; riverctl set-focused-tags $((1 << (2 - 1)))"
riverctl map normal Mod1 3 spawn "riverctl focus-output DP-2; riverctl set-focused-tags $((1 << (3 - 1)))"
riverctl map normal Mod1 4 spawn "riverctl focus-output DP-2; riverctl set-focused-tags $((1 << (4 - 1)))"
riverctl map normal Mod1 5 spawn "riverctl focus-output DP-2; riverctl set-focused-tags $((1 << (5 - 1)))"
riverctl map normal Mod1 6 spawn "riverctl focus-output DP-2; riverctl set-focused-tags $((1 << (6 - 1)))"
riverctl map normal Mod4 1 spawn "riverctl focus-output HDMI-A-1; riverctl set-focused-tags $((1 << (1 - 1)))"
#riverctl map normal Mod4+Shift 1 spawn "riverctl focus-output HDMI-A-1; riverctl set-view-tags $((1 << (1 - 1)))"

riverctl map normal Mod4 2 spawn "riverctl focus-output HDMI-A-1; riverctl set-focused-tags $((1 << (2 - 1)))"
riverctl map normal Mod4 3 spawn "riverctl focus-output HDMI-A-1; riverctl set-focused-tags $((1 << (3 - 1)))"
riverctl map normal Mod4 4 spawn "riverctl focus-output HDMI-A-1; riverctl set-focused-tags $((1 << (4 - 1)))"
riverctl map normal Mod4 5 spawn "riverctl focus-output HDMI-A-1; riverctl set-focused-tags $((1 << (5 - 1)))"
riverctl map normal Mod4 6 spawn "riverctl focus-output HDMI-A-1; riverctl set-focused-tags $((1 << (6 - 1)))"
# riverctl map normal Mod4+Shift 1 spawn "riverctl focus-output HDMI-A-1"

# Mod1+0 to focus all tags
# Mod1+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Mod1 0 set-focused-tags $all_tags
riverctl map normal Mod1+Shift 0 set-view-tags $all_tags

# Mod1+Space to toggle float
riverctl map normal Mod1 W toggle-float

# Mod1+F to toggle fullscreen 
riverctl map normal Mod1 F send-layout-cmd wideriver "--layout-toggle"
# riverctl map normal Mod1 F spawn "wideriver --layout-toggle"

# Mod1+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal Mod1 Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal Mod1 Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Mod1 Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Mod1 Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod1+F11 to enter passthrough mode
riverctl map normal Mod1 F11 enter-mode passthrough

# Mod1+F11 to return to normal mode
riverctl map passthrough Mod1 F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
# riverctl background-color 0x002b36
# riverctl border-color-focused 0xf3f2cc
# riverctl border-color-unfocused 0x232323

# Sloppy focus
riverctl cursor-follows-cursor always

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
# rivertile -view-padding 6 -outer-padding 6 &
riverctl rule-add ssd
riverctl default-layout wideriver
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --no-smart-gaps                            \
    --inner-gaps                   0           \
    --outer-gaps                   10          \
    --border-width                 2           \
    --border-width-monocle         0           \
    --border-width-smart-gaps      0           \
    --border-color-focused         "0xf3f2cc"  \
    --border-color-focused-monocle "0xf3f2cc"  \
    --border-color-unfocused       "0x232323"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

# Startup programs
riverctl focus-follows-cursor always

# Input
riverctl input pointer-13159-6500-Endgame_Gear_Endgame_Gear_OP1_8k_Gaming_Mouse accel-profile none
riverctl input pointer-13159-6500-Endgame_Gear_Endgame_Gear_OP1_8k_Gaming_Mouse pointer-accel -0.75

# Keyboard
riverctl keyboard-layout -options "caps:escape" us

# Output configuration
riverctl spawn "wlr-randr --output DP-2 --mode 1920x1080@240Hz"
riverctl spawn "wlr-randr --output HDMI-A-1 --mode 1920x1080@100Hz --transform 90"


# Wallpaper
riverctl spawn swww-daemon
#riverctl spawn "swww img --transition-type wipe --transition-angle 45 --transition-step 90 /home/autumn/Pictures/Wallpapers/woods.jpg"
# riverctl spawn "swww img --transition-type wipe --transition-angle 45 --transition-step 90 /home/autumn/Pictures/Wallpapers/Kita.png"
riverctl spawn "swww restore"

# Bar
riverctl spawn waybar
